# Generated by Django 3.1.5 on 2021-02-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.book')),
            ],
            bases=('catalog.book',),
        ),
        migrations.RemoveField(
            model_name='book',
            name='nr_of_pages',
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(choices=[('Litera', 'Litera'), ('Nemira', 'Nemira')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
