# Generated by Django 3.1.5 on 2021-02-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210208_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='book_id',
            new_name='book',
        ),
    ]
