# Generated by Django 3.1.5 on 2021-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210217_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
