# Generated by Django 3.1.5 on 2021-02-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
