# Generated by Django 3.1.5 on 2021-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_read',
            name='active',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
