# Generated by Django 3.1.5 on 2021-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_read_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literatura', 'Literatura'), ('Economie', 'Economie'), ('Dezvoltare personala', 'Dezvoltare personala'), ('Carti pentru copii', 'Carti pentru copii')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(choices=[('Litera', 'Litera'), ('Nemira', 'Nemira'), ('Curtea Veche', 'Curtea veche'), ('RAO', 'RAO')], max_length=100),
        ),
    ]
